### ISSUE TITLE
Strange space between panel and widgets

### ISSUE THREAD

**Issue by CavaleriOmar** [L4ki/Breeze-Noir-Dark#1]
Wonderful theme, but since the last Plasma update (on manjaro), the space between the panel and the floating widgets (such as simplemenu, avalon launcher or the notification widget) have moved up half a centimeter compared to the other themes (comparison done with the other themes I have on the PC as soon as this problem has arisen).

![Screenshot_20200802_192545](https://user-images.githubusercontent.com/54171779/89128744-1fe06900-d4f8-11ea-9057-2192d45e8a4a.png)

**Comment by L4ki** [comment]
Hi CavaleriOmar,

Thank you for the information.

How does it behave when you set up a classic Application Launcher?

**Comment by L4ki** [comment]
I reduced the distance between the Panel and the Application Launcher. I tried to keep the height of Application Launcher and Tooltips in the same line.

I think I succeeded.

Screenshoot: [![Screenshot-20200803-095056.png](https://i.postimg.cc/50fcMxqb/Screenshot-20200803-095056.png)](https://postimg.cc/4K226RSS)

What do you think?

I will publish the Update Theme on Friday: 07.08.2020.

**Comment by CavaleriOmar** [comment]
Wow, it's perfect!!!

Il lun 3 ago 2020, 10:02 L4ki <notifications@github.com> ha scritto:

**Comment by L4ki** [comment]
Ok, thank you very much!

Update: 07.08.2020.
