### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by ocm128** [L4ki/Breeze-Noir-Dark#2]
Sorry to ask this here, but are there any tips on how to install it? Thanks.

**Comment by L4ki** [comment]
Hi ocm128,

1. Automatically, via System Settings> Plasma Style> Get New Plasma Style ...> Search (type Breeze-Noir-Dark)> Install

2.Manually, download the zip file to https://store.kde.org/p/1361472/ and unzip it to: Dolphin (Show Hidden Files)> .local> share> plasma> desktoptheme

Although it is best to install Global Theme (Look and Feel), via System Settings> Global Theme> Get New Global Themes ...> Search (type Breeze-Noir-Dark)> Install
This way you will install: Plasma Theme, Colorscheme, Aurorae Theme, Icons, SDDM Theme, Splashscreen, Wallpapers. It means everything in one go.

Greeting,

**Comment by ocm128** [comment]
I will try it. Thank you very much L4ki!
