### ISSUE TITLE
How do you modify the color of the panel bar and app launcher background?

### ISSUE THREAD

**Issue by iswhy** [L4ki/Breeze-Noir-Dark#3]
I thought it is widgets/panel-background.svg but changing its color using inkscape does not seem to have any effect.

**Comment by L4ki** [comment]
Hi iswhy,

Panel color change is connected to: widgets > panel-background.svg

The color change Application Launcher is connected to: dialogs > background .svg

Example for Plasma Theme "Breeze-Noir-Dark" (Screenshot): https://ibb.co/vD8fxnq

Best regards,

**Comment by iswhy** [comment]
Hi thanks for the reply.
Now I notice that the color change does not take effect when there is an application that is maximized (that occupies the entire screen). But once I de-maximize it, the panel bar suddenly change to the color that I have chosen. Rebooting does not resolve the issue.

**Comment by L4ki** [comment]
Hi iswhy,

Yes, it depends on "Adaptive Transparency".

If you want, it may be: Adaptive, Opaque, Translucent

See Screenshot: https://ibb.co/WyPxf7V

**Comment by L4ki** [comment]
Note: If it is set to Adaptive or Opaque, the windows are maximized, the panel color monitors color from the "colors" file located within the Plasma Theme "Breeze-Noir-Dark".

If set to the Translucent will be the color you selected to modify panel-background.svg and dialogs background.svg

**Comment by iswhy** [comment]
I see, so it depends on the transparency setting.
By the way, which entry of the "color" file that corresponds to the panel bar color under opaque or adaptive setting?

**Comment by L4ki** [comment]
89 [Colors:Window]

91 BackgroundNormal=0,22,33   

Means you change RGB Decimal color label (0,22,33) 

rgb0,22,33 matches color #001621 

You set up you want .

Color encyclopedia : Information and conversion : https://www.colorhexa.com/
